.TH "EntityManager" 3 "Fri Oct 13 2017" "shrub" \" -*- nroff -*-
.ad l
.nh
.SH NAME
EntityManager
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "void \fBStart\fP ()"
.br
.ti -1c
.RI "void \fBUpdate\fP ()"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fBEntityBuilder\fP \fBm_entityBuilder\fP"
.br
.RI "The builder class which \fBEntityManager\fP uses to get Entities\&. "
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "void EntityManager\&.Start ()\fC [private]\fP"

.SS "void EntityManager\&.Update ()\fC [private]\fP"

.SH "Member Data Documentation"
.PP 
.SS "\fBEntityBuilder\fP EntityManager\&.m_entityBuilder\fC [private]\fP"

.PP
The builder class which \fBEntityManager\fP uses to get Entities\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for shrub from the source code\&.
