.TH "Enumerations" 3 "Fri Oct 13 2017" "shrub" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Enumerations
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBEntityTypes\fP { \fBEntityTypes\&.Human\fP = 0, \fBEntityTypes\&.Animal\fP = 1, \fBEntityTypes\&.House\fP = 2 }
.RI "Enumeration to support selection of entity types for methods\&. ""
.br
.ti -1c
.RI "enum \fBLandscapeTypes\fP { \fBLandscapeTypes\&.River\fP = 0, \fBLandscapeTypes\&.Mountain\fP = 1, \fBLandscapeTypes\&.Plain\fP = 2, \fBLandscapeTypes\&.Forest\fP = 3 }
.RI "Enumeration to support selection of entity types for methods\&. ""
.br
.in -1c
.SH "Member Enumeration Documentation"
.PP 
.SS "enum \fBEnumerations\&.EntityTypes\fP\fC [strong]\fP"

.PP
Enumeration to support selection of entity types for methods\&. 
.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIHuman \fP\fP
.TP
\fB\fIAnimal \fP\fP
.TP
\fB\fIHouse \fP\fP
.SS "enum \fBEnumerations\&.LandscapeTypes\fP\fC [strong]\fP"

.PP
Enumeration to support selection of entity types for methods\&. 
.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIRiver \fP\fP
.TP
\fB\fIMountain \fP\fP
.TP
\fB\fIPlain \fP\fP
.TP
\fB\fIForest \fP\fP


.SH "Author"
.PP 
Generated automatically by Doxygen for shrub from the source code\&.
