.TH "md__r_e_a_d_m_e" 3 "Fri Oct 13 2017" "shrub" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md__r_e_a_d_m_eREADME 
 \- This README would normally document whatever steps are necessary to get your application up and running\&.
.PP
.SS "What is this repository for?"
.PP
.IP "\(bu" 2
This is the repository for the code for Shrub\&.
.IP "\(bu" 2
\&.01a
.PP
.PP
.SS "How do I get set up?"
.PP
.IP "\(bu" 2
Summary of set up
.IP "\(bu" 2
Configuration
.IP "\(bu" 2
Dependencies
.IP "\(bu" 2
Database configuration
.IP "\(bu" 2
How to run tests
.IP "\(bu" 2
Deployment instructions
.PP
.PP
.SS "Contribution guidelines"
.PP
.IP "\(bu" 2
Writing tests
.IP "\(bu" 2
Code review
.IP "\(bu" 2
Other guidelines
.PP
.PP
.SS "Who do I talk to?"
.PP
.IP "\(bu" 2
Repo owner or admin
.IP "\(bu" 2
Other community or team contact 
.PP

