.TH "SceneManager" 3 "Fri Oct 13 2017" "shrub" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SceneManager
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "void \fBStart\fP ()"
.br
.ti -1c
.RI "void \fBUpdate\fP ()"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fBEntityManager\fP \fBm_entityManager\fP"
.br
.ti -1c
.RI "\fBLandscapeManager\fP \fBm_landscapeManager\fP"
.br
.RI "The manager class which \fBSceneManager\fP uses to get landscapes for the scene\&. "
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "void SceneManager\&.Start ()\fC [private]\fP"

.SS "void SceneManager\&.Update ()\fC [private]\fP"

.SH "Member Data Documentation"
.PP 
.SS "\fBEntityManager\fP SceneManager\&.m_entityManager\fC [private]\fP"
brief The manager class which \fBSceneManager\fP uses to get entities for the scene\&. 
.SS "\fBLandscapeManager\fP SceneManager\&.m_landscapeManager\fC [private]\fP"

.PP
The manager class which \fBSceneManager\fP uses to get landscapes for the scene\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for shrub from the source code\&.
